services:
  - type: web
    name: cricket-tournament-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_URL
        value: jdbc:mysql://caboose.proxy.rlwy.net:30613/railway?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - key: DB_DRIVER
        value: com.mysql.cj.jdbc.Driver
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: VFuBdipFGSCEyCAnrCOHNKBkzSuJCpHW
      - key: JPA_DIALECT
        value: org.hibernate.dialect.MySQLDialect
      - key: H2_CONSOLE
        value: "false"
      - key: DDL_AUTO
        value: update
      - key: CORS_ALLOWED_ORIGINS
        value: "https://tsauok.com,https://www.tsauok.com"
      - key: JWT_SECRET
        value: T5aUoK#cRiCkEt$2026!xQpLmNbVzJwRdYhSgFkTeAoIuCnMxBqPlWs
      - key: JWT_EXPIRATION_MS
        value: "86400000"
      - key: ADMIN_USERNAME
        value: thanoogithan_admin
      - key: ADMIN_PASSWORD
        value: Thanoo@2026
      - key: ADMIN_NAME
        value: thanoogithan sanmugarasa
      - key: SCORER_USERNAME
        value: thanoogithan_scorer
      - key: SCORER_PASSWORD
        value: Thanoo@2025
      - key: SCORER_NAME
        value: thanoogithan sanmugarasa
      - key: SPRING_PROFILES_ACTIVE
        value: prod
